# Set to true to print additional information when running demos
Verbose = false

# Specify the Diatheke server connection 
[Server]
    # Specify the server address as "<url>:<port>"
    Address = "localhost:9001"

    # Set to true if the server is running without a
    # secure (TLS) connection (not recommended for
    # production environments).
    Insecure = true

    # Specify the Diatheke model to use when creating new sessions.
    # This string should match one of the models defined in the Diatheke
    # server config file.
    ModelID = "1"

# If using audio input/output, specify the executables to handle
# recording and playback (e.g., sox). The encoding should match what
# is specified in the Diatheke server config file. The sample rate is
# defined by the underlying Cubic and Luna models.

# The recording app should output data to stdout
[Recording]
    # sox example (see http://sox.sourceforge.net/)
    Application = "sox"
    Args = "-q -d -c 1 -r 16000 -b 16 -L -e signed -t raw -"

# The playback app should accept input data from stdin
[Playback]
    # sox example (see http://sox.sourceforge.net/)
    Application = "sox"
    Args = "-q -c 1 -r 16000 -b 16 -L -e signed -t raw - -d"
